<a href="https://colab.research.google.com/github/FlamarokClass/EstructuraDeDatos/blob/master/PARCIAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Operador potencia: 5**2
#Operador // division
#Operador % resto de division
#Operador / division desimal

#CASTEO + INPUT
pedirTemp = float(input("Ingrese una  temperatura en grados Celsius "))

nombreCompleto = input("Indique su nombre completo: ")
print(nombreCompleto.upper()) # FRANCO ANDERSON
print(nombreCompleto.lower())  #franco anderson
print(nombreCompleto.capitalize()) # Franco anderson
print(nombreCompleto.title()) # Franco Anderson
#replace
#len(string)

if numero % 2 == 0:
  print(str(numero) + " es par")
elif numero % 2 == 1:
  print(str(numero) + " es impar")

# **FOR**

In [ ]:
#range(inicio, fin, paso)
#range(0,N,1) = range(N)
#range(2,9,2) -> 2,4,6,8
for var2 in range(5): #0,1,2,3,4
  print(var2)
  print("hola")
  print("chau")
#afuera del for

# **WHILE**

In [ ]:
varCondicion = 0
dato = 1
while varCondicion < 100:
  print(dato)
  varCondicion += 1
  dato +=1



# **Procedimiento**

In [ ]:
def procedimiento():
  print("Hola mundo!")

procedimiento()

# **Funcion**
Los valores pasados por parametros salen modificados

In [ ]:
def imprimirSaludo():
  nombre = input("Indique Su nombre: ")
  mensaje = print("Hola " + nombre.capitalize() +" !!!")
  return

n= imprimirSaludo()

###########################################################################################
def mayor():
  condicion = 0
  resultado = 0
  while condicion != 10:
    numero = int(input("Indique un valor entero positivo: "))
    condicion += 1
    if numero <= resultado:
      resultado = resultado
    elif numero >= resultado :
      resultado = numero
  return resultado

## 2da Manera con for

def maximo(num1,num2):
  maxNum = 0
  if num1 > num2:
    maxNum = num1
  else: maxNum = num2


mayor = None

for i in range(10):
  numero = float(input(f"Instroduce el número {i + 1 }: "))
  if mayor is None : # Primer numero ingresado
    mayor = numero
  else:
    mayor = maximo(mayor, numero)


n = mayor()

###########################################################################################

def areaCirculo(radio):
  calculo = 3.1416 * radio**2
  return calculo

def volumenCilindro(radio, altura):
  calculo = areaCirculo(radio) * altura
  return calculo

volumen = volumenCilindro(4,6)
print(f"el Volumen del cilindro es: {volumen}")


####################################################################################

def notas(primera,segunda,tercera):
  resultado = (primera + segunda + tercera) / 3
  if resultado >= 7:
    mensaje = "APROBADO"
  else: mensaje = "DESAPROBADO"
  return mensaje

nota = notas(4,4,6)
print(f"La Nota final es: {nota}")

##################################################################################
def esBiciesto(unAnio):
  resultado = False
  if (unAnio % 4 == 0 and unAnio % 100 != 0 or unAnio % 400 == 0):
      resultado = True
  else: resultado
  return resultado

anioUno= int(input("Indique un año: "))
anioDos= int(input("Indique otro año: "))

def cantidadDeBiciestos(primerAnio, segundoAnio):
  contador = 0
  for i in range(primerAnio,segundoAnio):
    if (esBiciesto(i) == True):
      contador += 1
  return contador

print(cantidadDeBiciestos(anioUno, anioDos))

##################################################################################

def cantidadDigitos(numero:int)->int:
  cantCifras = 0
  while numero!=0:
    numero //= 10
    cantCifras += 1
  return cantCifras
#3445//10 = 344
#3445%10 = 5
def sumaDigitos(numero:int)->int:
  sumaDeDigitos = 0
  while numero!=0:
    #print(numero)
    #print(numero//10)
    #print(numero%10)
    sumaDeDigitos += numero%10
    numero //= 10
  return sumaDeDigitos

#################################################################################

# **TDA**

**En cada ejercicio, luego de implementar el TDA pedido, tienen que probar cada una de las operaciones en un programa principal, ejecutando cada una de ellas**

**En el video les comenté de la función \_\_str__ para la representación de variables de los TDAs, en lugar de \_\_str__ pueden implementar \_\_repr__ que es similar pero más general (No solo sirve para el *print*, sino para la representación en general de variables del TDA)**


In [ ]:
def validarTipo2(variable, nombre, tipo, condicion = True):
  if isinstance(variable, tipo) and condicion:
    return variable
  else:
    raise Exception("La variable " + nombre + " debe ser de tipo " + str(tipo) + ". o falla la condicion "  )

def validarTipo(variable, nombre, tipo):
  if isinstance(variable, tipo):
    return variable
  else:
    raise Exception("La variable " + nombre + " debe ser de tipo " + str(tipo) + ".")

def validarAño(año):
  if validarTipo(año, "año", int) and año >= 1870:
    return año
  else:
    raise Exception("Año incorrecto")


def validarAltura(altura):
  if validarTipo(altura, "altura", float) and altura > 0:
    return altura
  else:
    raise Exception("Altura incorrecta")


In [ ]:
#TDA Auto
#cantPuertas -> int
#Marca -> str
#Modelo -> str
#cilindrada -> float

class Auto:
  def __init__(self, cantPuertas:int, marca:str, modelo:str, cilindrada:float):
    self.__cantidadPuertas = cantPuertas
    self.__marca = marca
    self.__modelo = modelo
    self.__cilindrada = cilindrada

  def __repr__(self):
    return f"{self.__marca}({self.__modelo})"

  def esIneficiente(self, cilLimite:float)->bool:
    return self.__cilindrada >= cilLimite

  def setMarca(self, marcaNueva:str):
    self.__marca = marcaNueva

In [ ]:
auto1 = Auto(5,"VW","gol",1.8)
print(auto1)


VW(gol)


In [ ]:
auto1 = Auto(5,"VW","gol",1.8)
print(auto1)
print(Auto.esIneficiente(auto1,1.5))
print(auto1.esIneficiente(1.5))
auto1.setMarca("Ford")
print(auto1)

VW(gol)
True
True
Ford(gol)


In [ ]:
#TDA como parametro de una funcion
def test(auto:Auto):
  auto.setMarca("Chevrolet")

In [ ]:
auto2 = Auto(4,"Ford","Fiesta",1.4)
print(auto2)
test(auto2)
print(auto2)

Ford(Fiesta)
Chevrolet(Fiesta)


In [ ]:
import copy #deepcopy
#Operador de asignacion
auto3 = Auto(4,"Ford","Fiesta",1.4)
auto4 = copy.deepcopy(auto3)
print(auto3)
print(auto4)
auto3.setMarca("VW")
print()
print(auto3)
print(auto4)

Ford(Fiesta)
Ford(Fiesta)

VW(Fiesta)
Ford(Fiesta)


In [ ]:
print(auto3.__marca)

DDD


In [ ]:
auto5 = Auto(3,"Chevrolet","Corsa",1.4)


### **Ejercicio 1**

Implementar el TDA "Propiedad" que modela un inmueble, con una estructura definida por los siguientes componentes:
- Calle
- Número
- Localidad
- Año de construcción
- Cantidad de ambientes

Implementar las siguientes operaciones:
- Constructor: Debe incluir las validaciones necesarias, teniendo en cuenta que solo se almacenan propiedades construidas luego de 1870.
- \_\_repr__: Al usar la función *print* con una variable del tipo propiedad debe mostrar: **'calle' 'numero' ('localidad')**.
- mismaLocalidad: Operación que recibe dos propiedades y retorna *True* si estan en la misma localidad y *False* en caso contrario.
- mayorNumeración: Operación que recibe dos propiedades y si están en la misma calle, retorna la que posee mayor numeración. Si están calles diferentes debe lanzar una excepción.
- calculaImpuestoARBA: Operación que retorna el porcentaje de impuesto inmobiliario de una propiedad, según la siguiente regla:
 - Propiedades entre 1870 y 1949:
   - Entre 1 y 3 ambientes: 5% de impuesto
   - Entre 4 y 6 ambientes: 10% de impuesto
   - Más de 6 ambientes: 25 % de impuesto
 - Propiedades desde 1950 hasta la actualidad:
   - Entre 1 y 5 ambientes: 5% de impuesto
   - Más de 5 ambientes: 35 % de impuesto


In [ ]:

class Propiedad:
  def __init__(self, calle:str, numero:int, localidad:str, anioConstruccion:int, cantAmbientes:int):
    self.__calle = calle.lower()
    self.__numero = validarTipo2(numero, numero, int, condicion = numero >= 0)
    self.__localidad = localidad.lower()
    self.__anioConstruccion = anioConstruccion
    self.__cantAmbientes = validarTipo2(cantAmbientes, cantAmbientes, int, condicion = cantAmbientes >= 0)

  def __repr__(self):
    return f"{self.__calle} {self.__numero} ({self.__localidad})"

  def mismaLocalidad(propiedadUno, propiedadDos) -> bool:
    respuesta = None
    if (propiedadUno.__localidad == propiedadDos.__localidad):
      respuesta = True
    else: respuesta = False
    return respuesta

  def mayorNumeracion(propiedadUno, propiedadDos) -> str:
    respuesta = None
    if (propiedadUno.__numero < propiedadDos.__numero and propiedadUno.__calle == propiedadDos.__calle):
      respuesta = propiedadDos
    elif(propiedadUno.__numero > propiedadDos.__numero and propiedadUno.__calle == propiedadDos.__calle):
      respuesta = propiedadUno
    else: raise Exception("Calle incorrecta")
    return respuesta


  def calculaImpuestoARBA(propiedad) -> float:
    respuesta = 0.0
    if (propiedad.__anioConstruccion > 1870 and propiedad.__anioConstruccion < 1949):
      if(propiedad.__cantAmbientes >= 1 and propiedad.__cantAmbientes<= 3):
        respuesta = 1.05
      elif(propiedad.__cantAmbientes >= 4 and propiedad.__cantAmbientes < 6):
        respuesta = 1.10
      elif(propiedad.__cantAmbientes >= 6):
        respuesta = 1.25
    elif(propiedad.__anioConstruccion > 1950):
      if(propiedad.__cantAmbientes >= 1 and propiedad.__cantAmbientes <= 5):
        respuesta = 1.05
      elif(propiedad.__cantAmbientes > 5):
        respuesta = 1.35
    return respuesta

casa = Propiedad("Origone", 370, "Villa Tesei", 1880, 6)

casa2 = Propiedad("Origone", 380, "Villa Tesei", 1990, 5)


print(casa)
print(Propiedad.mayorNumeracion(casa,casa2))
print(Propiedad.calculaImpuestoARBA(casa))

origone 370 (villa tesei)
origone 380 (villa tesei)
1.25


### **Ejercicio 2**

Implementar el TDA "Cuenta" que modela una cuenta bancaria, la estructura de datos esta compuesta por los siguientes componentes:
- Número de cuenta
- DNI del titular
- Saldo de cuenta actual
- Interés anual

Implementar las siguientes operaciones:
- Constructor: Debe incluir las validaciones necesarias.
- \_\_repr__: Al usar la función *print* con una variable del tipo cuenta debe mostrar: **Cuenta Nro: 'numero' - Titular: 'dni' ($'saldo')**.
- actualizarSaldo: Operación que actualiza el saldo de la cuenta aplicándole el interés diario (interés anual dividido entre 365).
- ingresarDinero: Operación que recibe un número e ingresa esa cantidad en la cuenta.
- retirarDinero: Operación que recibe un número y extrae esa cantidad de la cuenta (si hay saldo disponible), sino debe lanzar una excepción.

In [ ]:
class Cuenta:
  def __init__(self, numeroCuenta:int, dniTitular:int, saldoActual:float, interesAnual:float):
    self.__numeroCuenta = validarTipo(numeroCuenta, numeroCuenta, int)
    self.__dniTitular =  validarTipo2(dniTitular, dniTitular, int, condicion = dniTitular > 0)
    self.__saldoActual = saldoActual
    self.__interesAnual = interesAnual

  def __repr__(self):
    return f"Cuenta Nro: {self.__numeroCuenta} - Titular: {self.__dniTitular} (${self.__saldoActual})"

  def actualizarSaldo(self) -> float:
    self.__saldoActual += (self.__interesAnual / 360)

  def ingresarDinero(self, cantidadDinero:float)-> float:
    self.__saldoActual +=  cantidadDinero


  def retirarDinero(self, cantidadDinero:float) -> float:
    if(self.__saldoActual >= cantidadDinero):
      self.__saldoActual -= cantidadDinero
    else: raise Exception("Saldo no disponible")

  def getSaldo(self) -> int:
    return self.__saldoActual

cuenta1= Cuenta(123456, 40768233, 140.0, 1.10)
cuenta1.actualizarSaldo()
cuenta1.ingresarDinero(130.0)
cuenta1.retirarDinero(110.0)

cuenta1.getSaldo()

160.00305555555553

### **Ejercicio 3**

Implementar el TDA "Tiempo" que modela una duracion en horas, minutos y segundos.

Se deben implementar las siguientes operaciones:
- Constructor: Debe incluir las validaciones necesarias, la hora debe ser un número positivo y los minutos y segundos deben ser números positivos entre 0 y 59.
- \_\_repr__: Al usar la función *print* con una variable del tipo tiempo debe mostrar: **'horas':'minutos':'segundos'**.
- tiempoASegundos: Operación que toma una variable de tipo tiempo y retorna la cantidad en segundos.
- tiemposDesdeSegundos: Operación que recibe un tiempo en segundos como parámetro y retorna una variable de tipo tiempo, en horas minutos y segundos.
- mayorDuracion: Operación que recibe dos variables de tipo tiempo y retorna la de mayor duración.

In [ ]:
class Tiempo:
  def __init__(self, horas:int, minutos:int, segundos:int):
    self.__horas= validarTipo2(horas, horas, int, condicion = (horas <= 24 and horas >= 0))
    self.__minutos =  validarTipo2(minutos, minutos, int, condicion = (minutos <= 60 and minutos >= 0))
    self.__segundos = validarTipo2(segundos, segundos, int, condicion = (segundos <= 60 and segundos >= 0))

  def __repr__(self):
    return f"{self.__horas}:{self.__minutos}:{self.__segundos}"

  def tiempoASegundos(self) -> int:
    tiempo = (self.__horas * 3600) + (self.__minutos * 60) + self.__segundos
    return tiempo

  def tiemposDesdeSegundos(tiempoIndicado) -> int:
    horas = tiempoIndicado // 3600
    tiempoIndicado %= 3600
    minutos = tiempoIndicado // 60
    tiempoIndicado %= 60
    segundos = tiempoIndicado
    return Tiempo(horas, minutos, segundos)

  def mayorDuracion(tiempoUno, tiempoDos) -> "tiempo":
    resultado = None
    if(tiempoUno.__horas > tiempoDos.__horas):
      resultado = tiempoUno
    elif(tiempoUno.__horas == tiempoDos.__horas and tiempoUno.__minutos >= tiempoDos.__minutos):
      resultado = tiempoUno
    elif(tiempoUno.__minutos >= tiempoDos.__minutos and tiempoUno.__segundos >= tiempoDos.__segundos):
      resultado = tiempoUno
    else: resultado = tiempoDos
    return resultado

  def getHoras(self) -> int:
    return self.__horas

  def getMinutos(self)-> int:
    return self.__minutos

  def getSegundos(self)-> int:
    return self.__segundos

horario1 = Tiempo(23,30,28)
horario2 = Tiempo(21,35,27)

#print(horario1.tiempoASegundos())
#print(Tiempo.tiemposDesdeSegundos(88227))


print(Tiempo.mayorDuracion(horario1, horario2))

23:30:28



### **Ejercicio 4: TDA en dos niveles**

Modelar el TDA "Cronometro", que contiene un tiempo inicial y un tiempo final.

Se deben implementar las siguientes operaciones:

- Constructor: Queremos modelar el tiempo inicial y final con el TDA "Tiempo". Se pueden tener dos variables que se inicializaran en otra operación de la interface.
- Comenzar: Debe recibir las hs,min y seg iniciales.
- Finalizar: Debe recibir las hs,min y seg finales.
- TiempoEmpleado: Devuelve una variable de tipo Tiempo con la diferencia entre el tiempo inicial y el final.

In [ ]:
class Cronometro:
  def __init__(self, tiempoInicial = Tiempo(0,0,0), tiempoFinal = Tiempo(0,0,0)):
    self.__tiempoInicial = Tiempo(0,0,0) # validarTipo(tiempoInicial, "tiempoInicial", Tiempo)
    self.__tiempoFinal = Tiempo(0,0,0) # validarTipo(tiempoFinal, "tiempoFinal", Tiempo)

  def __repr__(self):
    return f"Tiempo Inicial: {self.__tiempoInicial} - Tiempo Final: {self.__tiempoFinal}"

  def comenzar(self,hs,min,seg) -> "tiempo":
    self.__tiempoInicial = Tiempo(hs,min,seg)
    return self.__tiempoInicial

  def finalizar(self,hs,min,seg)-> "tiempo":
    self.__tiempoFinal = Tiempo(hs,min,seg)
    return self.__tiempoFinal

  def tiempoEmpleado(self) -> "tiempo":
    if(self.__tiempoInicial.getHoras() >= self.__tiempoFinal.getHoras()):
      h = self.__tiempoInicial.getHoras() - self.__tiempoFinal.getHoras()
    elif(self.__tiempoInicial.getHoras() < self.__tiempoFinal.getHoras()):
      h = self.__tiempoFinal.getHoras() - self.__tiempoInicial.getHoras()

    if(self.__tiempoInicial.getMinutos() >= self.__tiempoFinal.getMinutos()):
      m = self.__tiempoInicial.getMinutos() - self.__tiempoFinal.getMinutos()
    elif(self.__tiempoInicial.getMinutos() < self.__tiempoFinal.getMinutos()):
      m = self.__tiempoFinal.getMinutos() - self.__tiempoInicial.getMinutos()

    if(self.__tiempoInicial.getSegundos() >= self.__tiempoFinal.getSegundos()):
      s= self.__tiempoInicial.getSegundos() - self.__tiempoFinal.getSegundos()
    elif(self.__tiempoInicial.getSegundos() < self.__tiempoFinal.getSegundos()):
      s= self.__tiempoFinal.getSegundos() - self.__tiempoInicial.getSegundos()
    resultado = Tiempo(h,m,s)
    return resultado

cronometro1 = Cronometro()
print(cronometro1)
cronometro1.comenzar(5,20,55)
cronometro1.finalizar(10,30,40)
print(cronometro1)
print(cronometro1.tiempoEmpleado())


Tiempo Inicial: 0:0:0 - Tiempo Final: 0:0:0
Tiempo Inicial: 5:20:55 - Tiempo Final: 10:30:40
5:10:15


### **Ejercicio 5: TDA en dos niveles**

Modelar el TDA "Rectangulo" a partir de los dos lados que lo definen.

Se deben implementar las siguientes operaciones:

- Constructor: Recibe las longitudes de ambos lados
- area: calcula y devuelve el area del rectangulo
- perimetro: calcula y devuelve el perimetro
- \_\_repr__ : imprime la longitud de los lados

Luego, modelar el TDA "Cuadrado" teniendo unicamente como variable interna en la estructura una variable de tipo "Rectangulo". El TDA Cuadrado debe tener las mismas operaciones que el TDA Rectangulo.

Ayuda:

Área(Rectángulo) = lado1 \* lado2

Área(Cuadrado) = lado^2

Perímetro(Rectangulo) = 2 \* lado1 + 2 \* lado2

Perímetro(Cuadrado) = 4 \* lado

In [ ]:
class Rectangulo:
  def __init__(self, ladoVertical: float, ladoHorizontal: float):
    self.__ladoVertical = ladoVertical
    self.__ladoHorizontal = ladoHorizontal

  def __repr__(self):
    return f"Largo Vertical: {self.__ladoVertical} - Lado Horizontal: {self.__ladoHorizontal}"

  def getLadoVertical(self)-> float:
    return self.__ladoVertical

  def getLadoHorizontal(self)-> float:
    return self.__ladoHorizontal

  def area(self)-> float:
    return self.__ladoVertical * self.__ladoHorizontal

  def perimetro(self)-> float:
    return (self.__ladoVertical * 2) + (self.__ladoHorizontal * 2)

class Cuadrado:
  def __init__(self, lado):
    self.__lado = Rectangulo(lado,lado)

  def __repr__(self) -> float:
    return f"Largo de sus lados es de: { self.__lado }"

  def area(self) -> float:
    return self.__lado.getLadoVertical() * self.__lado.getLadoHorizontal()

  def perimetro(self):
    return (self.__lado.getLadoVertical() * 2) + (self.__lado.getLadoHorizontal() * 2)

cuadrado1 = Cuadrado(5.0)

cuadrado1.area()
cuadrado1.perimetro()

20.0

### **Ejercicio 6**

Las plataformas de música online como ***YouTube*** y ***Spotify*** almacenan la información asociada a las canciones en estructuras de datos complejas para hacer las búsquedas de manera eficiente. Para esto se deben modelar las canciones. Implementar el TDA "Cancion" con los siguientes componentes:
- Nombre
- Artista
- Duración
- Género musical (6 posibles: Rock, Jazz, Blues, Funk, Reggae y Rap).
- Año de edición
- Número de likes

Implementar las siguientes operaciones:
- Constructor: Debe incluir las validaciones necesarias.
- \_\_repr__: Al usar la función *print* con una variable del tipo canción debe mostrar: **'nombre' - 'artista' ('duracion')**.
- mayorDuracion: Operación que recibe dos canciones por parámetros y retorna la de mayor duración.
- agregaLikes: Operación que recibe un número e incrementa la cantidad de likes de la canción en ese número.
- masVotada: Operacion que recibe dos canciones y sin son del mismo artista y del mismo género musical, retorna la que tiene mayor cantidad de likes. En caso contrario debe lanzar una excepción.

In [ ]:
class Cancion:
  def __init__(self, nombre : str, artista : str, duracion : float, genero : str, anio : int, likes : int):
    self.__nombre = nombre
    self.__artista = artista
    self.__duracion = duracion
    self.__genero = validarTipo2(genero, genero, str, condicion = genero == "Rock" or genero == "Jazz" or genero == "Blues" or genero == "Funk" or genero == "Reggae" or genero == "Rap").lower()
    self.__anio = anio
    self.__likes = likes

  def __repr__(self):
    return f"{self.__nombre} - { self.__artista} ({self.__duracion})"

  def mayorDuracion(cancionUno, cancionDos) -> "cancion":
    resultado = None
    if cancionUno.__duracion >= cancionDos.__duracion:
      resultado =  cancionUno
    else: resultado = cancionDos
    return resultado

  def agregaLikes(self, cantidad):
    self.__likes += cantidad
    return self.__likes

  def getLikes(self):
    return self.__likes

  def masVotada(cancionUno, cancionDos) -> "cancion":
    resultado = None
    if cancionUno.__artista == cancionDos.__artista and cancionUno.__genero == cancionDos.__genero and cancionUno.__likes >= cancionDos.__likes:
      resultado = cancionUno
    elif cancionUno.__artista == cancionDos.__artista and cancionUno.__genero == cancionDos.__genero and cancionUno.__likes < cancionDos.__likes:
      resultado = cancionDos
    else: raise Exception("No se puede hacer una comparacion")
    return resultado

velvet = Cancion("Velvet", "Dubliners", 1.20, "Rock", 1997,0)

road = Cancion("Road", "Dubliners", 1.30, "Rock", 2010, 0)

road.agregaLikes(10)
velvet.agregaLikes(15)

print(road.getLikes())
print(velvet.getLikes())

print(Cancion.mayorDuracion(road,velvet))
print(Cancion.masVotada(road,velvet))






10
15
Road - Dubliners (1.3)
Velvet - Dubliners (1.2)


### **Ejercicio 7**

Implementar el TDA "Quiniela" que modela un juego de quiniela con dos números premiados. La estructura contiene:
- Primer número premiado
- Segundo número premiado
- Multiplicador (cuánto se paga por cada peso apostado)

Implementar las siguientes operaciones:
- Constructor: Debe incluir las validaciones necesarias, teniendo en cuenta que los números que participan se encuentran entre 0 y 999.
- \_\_repr__: Al usar la función *print* con una variable del tipo quiniela debe mostrar: **Primer número ganador: 'numero' - Segundo número ganador: 'numero' - Paga: 'multiplicador'X**.
- esNumeroGanador: Operación que recibe un número por parámetros y retorna *True* si el número resultó ganador o *False* en caso contrario.
- importeAPagar: Operación que recibe un número y el monto apostado por parámetros y retorna el importe a pagar si la apuesta es ganadora o 0 en caso contrario. Si el número es el primer premio, se paga 'mutiplicador' por cada peso apostado, si es el segundo premio se paga la mitad. Solo se aceptan apuestas hasta $1000.
- premiadosCercanos: Operación que retorna *True* si los números premiados están a menos de 10 números de distancia y *False* en caso contrario.




In [ ]:
class Quiniela:
  def __init__(self, primerNumero:int, segundoNumero: int, multiplicador:int):
    if primerNumero >= 0 or segundoNumero < 999:
      self.__primerNumero = primerNumero
    if segundoNumero >= 0 or segundoNumero < 999:
     self.__segundoNumero = segundoNumero
    self.__multiplicador = multiplicador

  def __repr__(self):
    return f"Primer número ganador: {self.__primerNumero} - Segundo número ganador: {self.__segundoNumero} - Paga: {self.__multiplicador}X."

  def esNumeroGanador(self, numero)-> bool:
    respuesta = None
    if(numero == self.__primerNumero or numero == self.__segundoNumero):
      respuesta= True
    else: respuesta = False
    return respuesta

  def importeAPagar(self, numero, apuesta) -> int:
    respuesta = None
    if(numero == self.__primerNumero and apuesta > 0 and apuesta <= 1000):
      respuesta= apuesta * self.__multiplicador
    elif(numero == self.__segundoNumero and (apuesta > 0 and apuesta <= 1000)):
      respuesta = (apuesta * self.__multiplicador) / 2
    return respuesta

  def premiadosCercanos(self):
    respuesta = None
    for i in range(self.__primerNumero-1, (self.__primerNumero + 11)):
      if(i == self.__segundoNumero):
        respuesta = True
    for j in reversed(range(self.__primerNumero - 11, self.__primerNumero )):
      if(j == self.__segundoNumero):
        respuesta = True
    if respuesta == None:
      respuesta = False
    return respuesta



juego = Quiniela(90, 100, 4)

#print(juego.esNumeroGanador(15))
#juego.importeAPagar(50,20)

juego.premiadosCercanos()



True

# **RECURSIVIDAD**

### **Ejercicio 1**

Implementar una función que calcule el factorial de un número de forma recursiva

In [ ]:
def factorial(num):
  resultado = 0
  if num < 0:
    raise Exception("No es numero entero")
  if num == 0:
    return 1
  if num >= 0 :
    resultado = num * factorial(num-1)
    print(num,resultado)
    return resultado

print(factorial(5))

1 1
2 2
3 6
4 24
5 120
120


### **Ejercicio 2**

Una canilla de una casa pierde agua de forma que todos los días pierde 2 gotas más que el día anterior. Escribir una función recursiva que calcule cuantas gotas perderá la canilla el día N. El primer día solo perdía dos gotas.

In [ ]:
def canilla(dias):
  if dias < 0:
    raise Exception ("Debe ser un Numero entero")
  resultado = None
  elif dias == 1:
    return 2
  elif dias > 1:
    resultado = 2 + canilla(dias-1) # gotas del dia anterior + 2 gotas
    print(dias,resultado)
    return resultado

canilla1 = canilla(6)

2 4
3 6
4 8
5 10
6 12


### **Ejercicio 3**

Implementar una función recursiva que calcule los números de la serie de Fibonacci. La función para generar la serie de Fibonacci es la siguiente (donde N es el índice del número en la serie):

![alt text](https://matematicasmodernas.com/wp-content/uploads/2014/03/EcuacionF.jpg)

Luego escribir un programa que pida un número N (mayor o igual a 0) al usuario e imprima por pantalla los primeros N números de la serie de Fibonacci

Sobre la sucesion de Fibonacci: https://www.vix.com/es/btg/curiosidades/4461/que-es-la-sucesion-de-fibonacci




In [ ]:
def fibo(numero):
  resultado = 0
  if numero == 0:
    return 0
  elif numero == 1:
    return 1
  elif numero > 1 :
    resultado = fibo(numero-1) + fibo(numero-2) # ACA SI HAY UNA SUMATORIA
    print(numero, resultado)
    return resultado


fibo1= fibo(7)

2 1
3 2
2 1
4 3
2 1
3 2
5 5
2 1
3 2
2 1
4 3
6 8
2 1
3 2
2 1
4 3
2 1
3 2
5 5
7 13


### **Ejercicio 4**

Escribir una función recursiva que calcule el número triangular de índice N. El número triangular de índice N es la suma de todos los números desde 1 hasta N.

Algunos ejemplos:

*T(1) = 1*

*T(2) = 1 + 2*

*T(3) = 1 + 2 + 3*

*T(4) = 1 + 2 + 3 + 4*

*T(5) = 1 + 2 + 3 + 4 + 5*

...

*T(N) = 1 + 2 + 3 + 4 + ... + N*

In [ ]:
#T(N) = N + T(N-1)

def calcularNumeroTriangular(numero):
  calculo = 0
  if(numero < 0):
    raise Exception("No se puede")
  elif(numero == 1):
    return 1
  elif(numero > 1):
    calculo = numero + calcularNumeroTriangular(numero-1) # la variable almacena la suma de todos los numeros desde 1 a numero
    print(numero,calculo)
    return calculo

triangulo = calcularNumeroTriangular(4)

2 3
3 6
4 10


### **Ejercicio 5**

En las redes sociales se produce una continua interacción y cada vez que un usuario realiza una acción, la comunidad se modifica. Suponiendo que un *influencer* que usa ***Instagram*** cada vez que postea algo, aumenta su cantidad de seguidores según la siguiente regla:
- Durante los primeros 20 posteos, siempre suma una cantidad fija de 1000 (mil) seguidores en cada uno.
- A partir del posteo 21, la cantidad de seguidores duplica la cantidad previa de seguidores, mas  500 seguidores extra.

Implementar una función recursiva que permita saber cuantos seguidores tendra el *Instagramer* luego de una cantidad determinada de posteos.

In [ ]:
def validarPositivo(n):
  if n < 0:
    raise Exception("Numero negatico")

def seguidores(post):
  calculo = 0
  if(post == 0):   # 1 CASO BASE
    return 0
  elif(post == 1): # 2DO CASO BASE
    return 1000
  elif(1 < post <= 20):
    calculo = 1000 + seguidores(post-1)
    return calculo
  elif(post >= 21):
    calculo = 2* seguidores(post-1) +500
    print(calculo,post)
    return calculo


cacho= seguidores(25)

40500 21
81500 22
163500 23
327500 24
655500 25


### **Ejercicio 6**

Un equipo de albañiles de una obra, tiene que planificar la colocación de pisos. Dicha tarea se realiza teniendo algunas consideraciones específicas, que tienen que ver con el corte de las baldosas, con el material de pegado y la cantidad de trabajadores que hay en cada momento. En el arranque, el día uno (1), los albañiles colocan siempre 100 baldosas.
Luego, la cantidad que se coloca cada día se organiza de esta manera:
- Los días pares se colocan el doble de baldosas del día anterior.
- Los días impares (salvo el primer día) se coloca una cantidad igual a la suma de las que se colocaron los 2 dias anteriores.

Implementar una función que permita saber la cantidad de baldosas que se colocan un día determinado.

In [ ]:
# Recomendacion hacer 1ro la funcion que calcula la cant de baldosas para un dia determinado luego hacer otra fucion, que utlice la 1ra

def colocacion(dias): #cantidad en un dia determinado
  calculo = 0
  if(dias == 1):
    return 1000
  elif(dias % 2 == 0): #dias pares
    calculo = 2 * colocacion(dias-1)
    return calculo
  elif(dias %2 == 1 and dias != 1):
    calculo = colocacion(dias-1) + colocacion(dias-2)
    print(dias, calculo)
    return calculo

def acumBaldozas(n): # ACUMULADOR (formatos similares para todos los acum)
  if n == 1 :
    return colocacion(1)
  else: colocacion(n) + acumBaldozas(n-1) #

edificio1= colocacion(4)
print(edificio1)

3 3000
6000


### **Ejercicio 7**

Luego de una lluvia muy grande se acumula gran cantidad de agua en un estanque, durante el primer día, el agua comienza a ponerse de color verde y un grupo de científicos decide medir cuantas algas encuentra dentro del tanque. La primer medición le da como resultado 12 algas. Luego deciden ir a realizar la medición todos los días para tratar de establecer un patrón de crecimiento y se encuentran que las algas crecen con la siguiente regla:
- Durante los siguientes 10 días (del dia 2 al 11) la cantidad de algas en el tanque es 15 más de las que había el día anterior.
- A partir del día 12, la cantidad de algas en el tanque es el triple de las que había el día previo más una cantidad fija de 100.

Escriba una función recursiva que calcule la cantidad de algas en el tanque en un día N.

Nota: Suponer que no mueren algas en el tanque.

In [ ]:
def algas(dias):
  if(dias == 1):
    return 12
  if(dias >= 2 and dias <= 11):
    calculo = 15 + algas(dias-1)
    return calculo
  if(dias >= 12):
    calculo = 3 * algas(dias-1) + 100
    print(dias,calculo)
    return calculo

tanque1 = algas(5)
tanque2 = algas(13)
print(tanque1)
print(tanque2)

12 586
13 1858
72
1858


### **Ejercicio 8**

Escribir una función recursiva que calcule la potencia N de un número M (M a la N), ambos números enteros positivos.   

In [ ]:
#M^N = M * M * M * .....* M (N veces) = M * M^(N-1)
#Piensen caso base

#M² = M*M
#M³ = M*M*M
#M⁴ = M*M*M*M

def potenciacion(base : int, exponente: int):
  if(exponente == 0):
    return 1
  if(exponente == 1):         #CASO BASE
    return base
  if(exponente >= 2):
    calculo = base * potenciacion(base,exponente-1)
    print(exponente,calculo)
    return calculo

potencia1 = potenciacion(2,5)
print(potencia1)

2 4
3 8
4 16
5 32
32


### **Ejercicio 9**

Problema del trigo en el tablero de ajedrez:

![alt text](https://i0.wp.com/matematicascercanas.com/wp-content/uploads/2015/03/leyenda_ajedrez.jpg?w=600&ssl=1)

Si se colocase sobre un tablero de ajedrez, un grano de trigo en el primer casillero, dos en el segundo, cuarto en el tercero y asi sucesivamente, doblando la cantidad de granos en cada casilla ¿Cuantos granos de trigo habría en el tablero en total al final? Resolver el problema con una función recursiva.

Leyenda del Trigo y el tablero de ajedrez y mas datos: https://matematicascercanas.com/2014/03/10/la-leyenda-del-tablero-de-ajedrez-y-los-granos-de-trigo/

In [ ]:
#cantidadGranosEnTablero(cantCasilleros) = cantidadGranosEnCasillero(cantCasilleros) + cantidadGranosEnTablero(cantCasilleros-1)
# Acumula los de la operacion anterior.

def cantidadDeGranosEnCasillero(cantCasilleros): # resuelve la cantidad de un casillero determinado
  if(cantCasilleros == 1):
    return 1
  if(cantCasilleros >= 2 ):
    calculo = 2 * cantidadDeGranosEnCasillero(cantCasilleros-1)
    return calculo

def cantidadDeGranosEnTablero(cantCasilleros): # acumulador
  calculo = 0
  if(cantCasilleros == 1):
    return 1
  else:
    calculo = cantidadDeGranosEnCasillero(cantCasilleros) + cantidadGranosEnTablero(cantCasilleros-1)
    print(cantCasilleros, calculo)
    return calculo

tablero = cantidadDeGranosEnTablero(5)
print(tablero)

5 25
25


### **Ejercicio 10**

En un edificio alto, las cucarachas se van distribuyendo por pisos de esta forma:
- En el primer piso hay una cucaracha
- En los pisos pares el doble del número de piso (por ejemplo en el piso 8 hay 16 cucarachas)
- El resto de los pisos tienen la suma de las cucarachas de los dos pisos anteriores.

Escribir una función recursiva que calcule la cantidad de cucarachas en un edificio en función de la cantidad de pisos.

In [ ]:
def cucarachasPorPiso(pisos:int):
  if(pisos < 0):
    raise Exception("Debe ser un valor positivo")
  elif(pisos == 0):
    return 0
  elif(pisos == 1):
    return 1
  elif (pisos > 1 and pisos % 2 == 0):
    calculo = 2 * pisos
    return calculo
  elif(pisos > 1 and pisos % 2 != 0):
    calculo = cucarachasPorPiso(pisos-1) + cucarachasPorPiso(pisos-2)
    return calculo

def cucarachasEnElEdificio(pisos, cucas): # Acumulador
  if(pisos == 0):
    totalCucas = cucas
  else:
    totalCucas= cucarachasEnElEdificio(pisos -1, cucas + cucarachasPorPiso(pisos))

piso7= cucarachasPorPiso(7)
piso8= cucarachasPorPiso(8)
piso9= cucarachasPorPiso(9)
print(piso7)
print(piso8)
print(piso9)

25
16
41


### **Ejercicio 11**

Escribir la función recursiva repetirPalabra, que recibe como parámetro una palabra (cadena de caracteres) y un número N. La función debe retornar una nueva cadena que contenga la palabra repetida N veces, por ejemplo:

*repetirPalabra("hola",3) -> "holaholahola"*

In [ ]:
#repetirPalabra("hola",2) -> "holahola"
#repetirPalabra("hola",3) -> "holaholahola"
#repetirPalabra("hola",4) -> "holaholaholahola"
#....
#repetirPalabra(palabra, N) = repetirPalabra(palabra, N-1) + palabra
#Pensar el caso base

def repetirPalabra(palabra : str,  cantidad : int):
  if (cantidad <= 0 ):
    raise Exception("Debe ser un entero positivo")
  if(cantidad == 1):
    return palabra
  if(cantidad > 1):
    calcular = palabra + repetirPalabra(palabra, cantidad-1)
    return calcular

mensaje1= repetirPalabra("franco",4)
print(mensaje1)

francofrancofrancofranco


### **Ejercicio 12**

Escribir una función recursiva que calcule el número combinatorio, es decir, las combinaciones de N elementos tomados de a M, usando la siguiente expresión:

![numeroCombiantorio.png](https://i.ibb.co/y408VDB/numero-Combiantorio.png)

In [ ]:
def combinartirio(n, m):
  if m <= 0 or n<=0 or n< m:
    raise Exception
  elif (m ==1):
    resultado = n
  elif m == n:
    resultado = 1
  else:
    resultado = combinartirio(n-1, m-1) + combinartirio(n, m-1)



# **VECTORES**

> Tamaño fijo con todos sus elementos numericos del mismo tipo


*    Son unidimensionales

*  vector2 = vector1 # nueva refencia a vector 1, pero la posicion en memoria es la misma para eso inicio la variable le indico que tenga el largo del vector1 y le ingreso los datos por iteracion





## **Declaracion de vectores**

In [ ]:
import numpy as np # np hace refencia a numpy

vector = np.zeros(10, int) # declaramos un vector de 10 enteros (todos 0)
otroVector = np.array([1,2,3,4,5])
print(len(vector)) #"Longitud de vector (cantidad de elementos)"


## **Acceso con indices / posiciones**

In [ ]:
vector[0] = 20 # en la posicion 0 le cargamos un 20
vector[5] = 10 # en la posicion 5 le cargamos un 10
 #vector[10] = 58 # la posicion 10 no existe, porque llega hasta 9, deberia de dar un error del 0 al 9 (posiciones) pero son 10 elementos
#print(vector[2:6]) # accedemos al elemento utilizando rangos, de 2 hasta 5

## **Recorridos de vectores**

In [ ]:
import numpy as np

vector = np.array([3,5,1,8,14]) # declaramos vector de enteros

print(vector)
print("Recorrido sobre elementos directamente (sentido directo)")
for elemento in vector:
  print(elemento)

print("\n", vector)
print("Recorrido sobre elementos directamente (sentido inverso)")
for elemento in reversed(vector):
  print(elemento)

print("\n", vector)
print("Recorrido usando indices / posiciones (sentido directo)")
for posicion in range(len(vector)): #len de vector es 5, el rango de 0 hasta 4
  print("Posicion: ", posicion) # imprime el valor de posicion (0,1,2,3,4)
  print(vector[posicion]) # imprimi el elemento del vector en esa posicion

print("\n", vector)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicion in reversed(range(len(vector))):
  print("Posicion: ", posicion)
  print(vector[posicion])

## **Arreglos de caracteres y tipo str**

In [ ]:
import numpy as np

########### Arreglos de caracteres ###########
print("########### Arreglos de caracteres ###########")

cadena = np.array(["hr","or","l","a"]) # declaramos arreglo de caracteres

print(cadena)
cadena [1] = "f" # modificamos el elemento en posion 1
print(cadena)

########### Tipo Str ###########
print("########### Tipo Str ###########")

cadenaStr = "hola"  # declaramos una variable de tipo str

print(cadenaStr)
print(cadenaStr[0]) # accedemos al elemento en posicion 0, podemos leer

#cadenaStr[1] = "f" # no me deja ya que es inmutable, no se puede modificar, no se puede escribir

########### Arreglos de caracteres ###########
['hr' 'or' 'l' 'a']
['hr' 'f' 'l' 'a']
########### Tipo Str ###########
hola
h


## **Arreglos como parametros de funciones / procedimientos**

In [ ]:
import numpy as np

def funcionEjemplo(vector): # recibe por parametro un vector
  vector[1] = 20 #lo modifica
  return

v = np.array ([2,5,3,9])

print("v: ", v)

funcionEjemplo(v)

print("\nLuego de ejecutar funcionEjemplo") # paso por referencia, las modificaciones valen afuera de la funcion
print("v: ", v)

v:  [2 5 3 9]

Luego de ejecutar funcionEjemplo
v:  [ 2 20  3  9]


### **Ejercicio 1**

Escribir una función que recibe un numero entero N y le pide al usuario que ingrese N numeros. Al final, el programa debe retornar un vector contiendo los números que fueron ingresados. Tambien debe imprimir por pantalla la suma total de los valores y el promedio. Se deben hacer funciones para resolver el promedio y la suma total.

In [ ]:
import numpy as np
def sumaTotal(vector:np.array)->int:
  suma = 0 #Inicializo la variable "suma" en 0
  for valor in vector: #Para cada valor en el vector:
    suma += valor #suma será el valor que hay en la variable "suma" más el "valor" actual que haya tomado del vector
  #Suma iterando por las posiciones
  #for pos in range(len(vector)):
  #  suma += vector[pos]
  return suma #Una vez que termine de iterar devolvemos el valor de la variable "suma"

def promedio(vector:np.array)-> float:
  return sumaTotal(vector)/len(vector) #El promedio es la suma de los elementos dividida la cantidad de elementos

def ingresarEnteros(N:int)->np.array:
  salida = np.zeros(N, int) #Inicializo la salida con un vector de ceros
  for pos in range(len(salida)): #0,1,2,3,4,....,N-1 #Obtengo los índices
    salida[pos] = int(input("Ingrese un numero: ")) #Asigno a cada lugar del vector, un número ingresado por el usuario
  print(sumaTotal(salida)) #Retorno el valor de la suma
  print(promedio(salida)) #Retorno el valor del promedio
  return salida #Retorno el vector ingresado por el usuario

v = ingresarEnteros(3)
print(v)

Ingrese un numero: 1
Ingrese un numero: 2
Ingrese un numero: 3
6
2.0
[1 2 3]


### **Ejercicio 2**

Escribir una función que recibe un vector de strings y retorna otro con los mismos elementos del vector de entrada pero en orden inverso.

In [ ]:
def invertirArreglo(vector:np.array)->np.array:
  vectorInvertido = np.zeros(len(vector), str) #Inicializo un vector de ceros
  pos = 0 #Inicializo la variable posición para ir iterando en el vector
  for valor in reversed(vector): #Itero los valores en el vector invertido
    vectorInvertido[pos] = valor #Asigno a mi vector de ceros, para cada lugar, un valor (tomados invertidos del vector original)
    pos += 1 #Incremento mi contador de vector invertido
  return vectorInvertido #Retorno el valor invertido

palabra = np.array(["h","o","l","a","c","o","m","o"])
print(palabra)
print(invertirArreglo(palabra))

['h' 'o' 'l' 'a' 'c' 'o' 'm' 'o']
['o' 'm' 'o' 'c' 'a' 'l' 'o' 'h']


In [ ]:
"hola"[::-1]

'aloh'

In [ ]:
def stringInversor1(stringVector:np.array)->np.array: #Otra forma de pensarlo es invertir los strings, dentro de un vector
  salida = np.zeros(len(stringVector)).astype(str) #Inicializo mi vector de salida con ceros

  for i in range(len(stringVector)): #Itero en lo índices del vector de entrada
    salida[i] = stringVector[i][::-1] #Cada elemento del vector de entrada es un string, que puedo manipular como un vector. Recorro todos los elementos de atrás para adelante

  return salida #Retorno el valor de salida con cada string invertido.

misStrings = np.array(["Hola" , "Mundo" , "Como" , "Estas"])

print(stringInversor1(misStrings))

['aloH' 'odnuM' 'omoC' 'satsE']


In [ ]:
def stringInversor2(stringVector:np.array)->np.array: #Otra forma de hacer la versión que vimos antes:
  salida = np.zeros(len(stringVector)).astype(str) #Inicializo mi vector de salida en cero

  for i in range(len(stringVector)): #Para cada índice en el rango del vector de strings
    salida[i] = stringVector[len(stringVector)-(i+1)] #Asignamos a la salida el último elemento: tamaño del vector menos el índice que estamos recorriendo

  return salida #Devolvemos la salida

print(stringInversor2(misStrings))

['Estas' 'Como' 'Mundo' 'Hola']


### **Ejercicio 3**

Escribir la función sumaDeVectores que recibe dos vectores de enteros del mismo tamaño y retorna otro con la suma de ambos. La suma de vectores se realiza componente a componente, segun la siguiente forma:

v<sub>1</sub> = [ v<sub>11</sub> , v<sub>12</sub> , v<sub>13</sub> , ... , v<sub>1N</sub> ]

v<sub>2</sub> = [ v<sub>21</sub> , v<sub>22</sub> , v<sub>23</sub> , ... , v<sub>2N</sub> ]

v<sub>1</sub> + v<sub>2</sub> = [ v<sub>11</sub> + v<sub>21</sub> , v<sub>12</sub> + v<sub>22</sub> , v<sub>13</sub> + v<sub>23</sub> , ... , v<sub>1N</sub> + v<sub>2N</sub> ]

In [ ]:
def sumaVectores(v1:np.array, v2:np.array)->np.array:
  salida = np.zeros(len(v1), int) #Inicializo mi vector de salida con ceros
  for posicion in range(len(salida)): #Itero sobre los índices
    salida[posicion] = v1[posicion] + v2[posicion] #A cada posición del vector de salida le asigno la suma de ambos vectores
  return salida #Retorno la salida

suma = sumaVectores(np.array([2,3,4,5]),np.array([5,1,2,3]))
print(suma)

[7 4 6 8]


In [ ]:
def sumaDeVectores(vec1:np.array , vec2:np.array)->np.array: #Otra forma de ver lo mismo
  N = len(vec1) #Me interesa N porque es el parámetro de todos mis vectores
  if N != len(vec2): #Valido que los vectores que voy a sumar tengan el mismo tamaño
    raise Exception(f"Los vectores deben tener el mismo Tamaño! vec1 tiene {len(vec1)} elementos y vec2 tiene {len(vec2)}") #lanzo una excepción

  resultado = np.zeros(N) #Inicializo el vector resultado con N ceros

  for i in range(N): #Itero sobre los índices
    resultado[i] = vec1[i] + vec2[i] #Asigno en cada posición la suma de ambos vecores

  return resultado #Retorno el resultado

vec1 = np.array([1 , 2 , 3])
vec2 = np.array([4 , 5 , 6])
#vec3 = np.array([7 , 8 , 9 , 10])

print(sumaDeVectores(vec1 , vec2))
#print(sumaDeVectores(vec2 , vec3))

[5. 7. 9.]


### **Ejercicio 4**

Escribir una función que recibe un vector y desplaza todos sus elementos una posición hacia la derecha: el primero pasa a ser el segundo, el segundo pasa a ser el tercero y así sucesivamente. El último pasa a ser el primero.

Por ejemplo:

v1 = [2, 4, 1, 5, 7, **9**]

**desplazarADerecha(v1)**

=> v1 = [**9**, 2, 4, 1, 5, 7]

In [ ]:
def desplazarADerecha(vector:np.array)->None: #En este caso devuelvo el mismo vector modificado
  ultimo = vector[len(vector)-1] #9 #Tomo el último valor
  for pos in reversed(range(0, len(vector)-1)): #range(0,5) -> 0,1,2,3,4 #Itero sobre los valores menos uno (por  que tengo el último)
    #pos = va desde 4 hasta 0
    vector[pos+1] = vector[pos]  #vector[1] = vector[0] #Muevo todos los números a la derecha
  v[0] = ultimo #Asigno mi último a la posición cero

v = np.array([2, 4, 1, 5, 7, 9])
print(v)
desplazarADerecha(v)
print(v)

[2 4 1 5 7 9]
[9 2 4 1 5 7]


In [ ]:
def desplazarADerecha(vector: np.array)-> None:#Como hacerlo con un vector intermedio
  vectorDesplazado = np.zeros(len(vector), int) #Inicializo mi vector intermedio de ceros
  vectorDesplazado[0] = vector[-1] #Inciailizo el primer elemento de mi vector resultado con
  for pos in range(1, len(vector)): #Para cada índice empezando desde 1, porque el 0 ya lo tengo asignado
        vectorDesplazado[pos] = vector[pos-1] #La posición de ese vector será la posición anterior del vector original (de esta forma desplazo a la derecha)
  for pos in range(len(vectorDesplazado)): #Ahora para cada índice (cualquiera de los dos vectores)
    vector[pos] = vectorDesplazado[pos] #Asigno en mi vector original los valores tal cual del vector intermedio

v1  = np.array([2, 4, 1, 9, 8])
print(v1)
desplazarADerecha(v1)
print(v1)

[2 4 1 9 8]
[8 2 4 1 9]


In [ ]:
def posicionADerecha(vector1):
  nuevoVector = np.zeros(len(vector1), int)
  for posicion in range(len(vector1) - 1):
    nuevoVector[posicion + 1] = vector1[posicion]
  nuevoVector[0] = vector1[len(vector1) - 1]
  vector1 = nuevoVector
  return vector1

In [ ]:
def desplazarVectorDer(vector:np.array)->None: #Más compacto
  arrAux = np.array(vector) #copio el vector
  for i in range(len(vector)): #Le asigno a cada posición la posición anterior
    vector[i] = arrAux[i-1]    ###Esta usando la posicion -1 en la primer iteracion

v1  = np.array([2, 4, 1, 9, 8])
print(v1)
desplazarVectorDer(v1)
print(v1)

[2 4 1 9 8]
[8 2 4 1 9]


### **Ejercicio 5**

Desarrollar una función que inserte un elemento en una posición en un vector. Al insertar el elemento, se debe producir un desplazamiento a la derecha de todos los elementos en las posiciones siguientes, el último elemento se pierde.

Por ejemplo:

v1 = [2, 4, 1, 7, 6, 2]

**insertar(v1, 5, 3)** #insertamos un 5 en la posición 3

=> v1 = [2, 4, 1, **5**, 7, 6]

In [ ]:
def insertar(arr, pos, val):
  for i in reversed(range(pos, len(arr)-1)): #Tomo los índices desde la posicion donde quiero insertar hasta el anteúltimo (dado que el último se pierde). Lo invierto (para empezar de atrás hacia adelante)
    print(i+1, i) #Para control veo cuáles son los índices que estoy trabajando
    arr[i+1] = arr[i] #En una primera iteración, i debe ser el anteúltimo elemento. Por lo que i+1 es el último elemento, asigno como último al anteúltimo. Así sigo hast la posición en la que voy a insertar
  arr[pos] = val #una vez llegado tanto pos como pos+1 son el mismo número. Le asigno el valor que quiero insertar

arr1 = np.array([2, 4, 1, 7, 6, 2])
insertar(arr1, 3, 5)
print(arr1)

5 4
4 3
[2 4 1 5 7 6]


In [ ]:
def insertar2(vector:np.array , numero:int , posicion:int)->np.array: #Otra forma de verlo:
  N = len(vector) #Tamaño de mi vector
  for i in range(N-1 , posicion , -1): #Armo un rango desde el anteúltimo índice, hasta la posición que quiero, avanzando de a -1 (para atrás)
    vector[i] = vector[i-1] #Asigno a cada posición, el valor anterior

  vector[posicion] = numero #En la posición de interés agrego el número

  return vector #Retorno el vector

v1 = [2, 4, 1, 7, 6, 2]

print(insertar2(v1 , 5 , 3))

[2, 4, 1, 5, 7, 6]


### **Ejercicio 6**

Escribir una función que elimine el elemento que ocupa una determinada posición de un vector. Al eliminar, los elementos a la derecha del eliminado, deben desplazarse a la izquierda un lugar y agregar un cero en la última posición.

Por ejemplo:

v1 = [4, 3, **5**, 8, 6, 7]

**eliminar(v1, 2)** #eliminamos el elemento de la posicion 2

=> v1 = [4, 3, **8, 6, 7, 0**]

In [ ]:
#v1 = [3, 5, 8, 6, 7, 7] 0 -> len(v1)-2 -> range(0,len(v1)-1)

def eliminar(vector:np.array, posDel:int)->None:
  if 0 <= posDel < len(vector): #Primero valido que la posición a eliminar esté dentro del rango de nuestro vector
    for pos in range(posDel,len(vector)-1): #Para cada posición entre el indice que eliminaremos y el tamaño del vector:
      vector[pos] = vector[pos+1] #Asignamos a cada posición el valor de su derecha
    vector[len(vector)-1] = 0 #Ponemos un cero en la última posición
  else: #En caso que no esté el valor a eliminar dentro del rango:
    raise IndexError("Posicion incorrecta") #Lanzamos un error

v1  = np.array([4, 3, 5, 5, 6, 7])
print(v1)
eliminar(v1,2)
print(v1)
eliminar(v1,2)
print(v1)

[4 3 5 5 6 7]
[4 3 5 6 7 0]
[4 3 6 7 0 0]


### **Ejercicio 7**

Escribir una función que elimine todas las apariciones de un determinado elemento de un vector. Al eliminar se deben insertar tantos ceros al final como elementos se eliminaron.

Por ejemplo:

arr1 = [4, 3, 5, 8, 6, 5, 7, 5]

**eliminarApariciones(arr1, 5)** #eliminamos todos los 5 del arreglo

=> arr1 = [4, 3, 8, 6, 7, **0, 0, 0**]

In [ ]:
#Recorrer array y usar funcion del ejercicio 5 para eliminar los elementos de a uno
def eliminarApariciones(vector:np.array, datoDel:int)->None:
  pos = 0 #Inicializo un contador en cero
  while pos < len(vector): #Mientras el contador sea menor que el tamaño del vector:
    if vector[pos] == datoDel: #Si el elemento de la posición POS coincide con el dato a eliminar:
      eliminar(vector, pos) #Reciclamos el código, llamamos a la función eliminar que lo elimina, desplaza todos los números a la izquierda y agrega un cero en último lugar
    #Notemos acá que si elimina, en la próxima iteración volvemos a ver el mismo lugar porque en POS está el valor que antes estaba a la izquierda
    else:
      pos += 1 #Si el valor no coincide, incrementamos el valor del contador y seguimos iterando
v3 = np.array([4, 3, 5, 8, 6, 5, 7, 5])
print(v3)
eliminarApariciones(v3,5)
print(v3)

[4 3 5 8 6 5 7 5]
[4 3 8 6 7 0 0 0]


### **Ejercicio 8**

Escribir un procedimiento que reciben un vector y:
- Imprime un subvector con los dos primeros elementos.
- Imprime un subvector con los tres últimos elementos.
- Imprime un subvector con los elementos desde la posiciones 2 hasta la 5
- Imprime un subvector con los elementos alternados cada dos. Por ej.: v1 = [2 , 1 , 4 , 5 , 2 , 7 , 9] debería imprimir [2 , 4 , 2 , 9]

Nota: Se debe utilizar la notacion **vector [ pos<sub>inicio</sub> : pos<sub>fin</sub> ]**

In [ ]:
def subVectores(unVector:np.array)->None:
  N = len(unVector) #Guardo el tamaño de mi vector
  subVector1 = unVector[0:2] #Tomo los dos primeros elementos. Recordemos que es [0:2), el 2 no está incluído
  subVector2 = unVector[-3:N] #Tomo los últimos tres elementos (desde -3 hasta N-1)
  subVector3 = unVector[2:5+1] #Tomo los elementos desde el 2 hasta el 5 (dejo explícito que es 5+1 porque el último no está incluído)
  subVector4 = unVector[0:N:2] #Tomo los elementos del primero al último saltando de a dos

  print(f'Los dos primeros elementos son {subVector1}')
  print(f'Los últimos tres elementos son {subVector2}')
  print(f'Los elementos desde la posición 2 hasta la 5 son {subVector3}')
  print(f'Los elementos alternados cada dos son {subVector4}')

  return

v1 = np.array([2 , 1 , 4 , 5 , 2 , 7 , 9])

subVectores(v1)

Los dos primeros elementos son [2 1]
Los últimos tres elementos son [2 7 9]
Los elementos desde la posición 2 hasta la 5 son [4 5 2 7]
Los elementos alternados cada dos son [2 4 2 9]


In [ ]:
arr1 = np.array([4, 3, 5, 8, 6, 5, 7, 5])
#print(arr1[2:6])

print(arr1[:2]) #primeros 2
print(arr1[len(arr1)-3:]) #ultimos 3
print(arr1[2:6])
print(arr1[::2])

[4 3]
[5 7 5]
[5 8 6 5]
[4 5 6 7]


In [ ]:
miVector = np.array([1 , 2 , 3 , 4 ,5])
print(miVector[0])
print(miVector[1:])
print(miVector[1:][0])
print(miVector[1:][1:])

miVectorSolito = np.array([45])
print(miVectorSolito[1:])

1
[2 3 4 5]
2
[3 4 5]
[]


### **Ejercicio 9**

Escribir una función **recursiva** que reciba un vector como parámetro y retorne la suma de todos sus elementos.

In [ ]:
#v1 = [2,3,1,5,4]
#suma(v1) = 2+3+1+5+4 = 2 + (3+1+5+4)
#suma(v) = v[0] + suma(v[1:])    si len(v) > 0
#           0                    si len(v) = 0

def sumaRecursiva(vector:np.array)->int:
  sumaTotal = None #Inicializo mi variable de salida como None
  if len(vector) == 0: #Si el vector de entrada está vacío:
    sumaTotal = 0 #La suma total es cero
  else: #Sino:
    sumaTotal = vector[0] + sumaRecursiva(vector[1:]) # 2 + sumaRecursiva([3,1,5,4]) #EL valor de la suma será el primer elemento del vector más la suma del subvector que contiene todos los elementos menos el primero
  return sumaTotal #Retorno el valor de la suma total

  #sumaTotal = vector[0] + vector[1] + vector[2] + .... + vector[N]
  #sumaTotal = vector[0] + vector[1:][0] + vector[1:][1:][0] + .... + 0

v1 = np.array([2,3,1,5,4])
print(sumaRecursiva(v1))

15


In [ ]:
#v1 = [2,3,1,5,4]
#suma(v1) = 2+3+1+5+4 = 2 + (3+1+5+4)
#suma(v) = v[0] + suma(v[1:])    si len(v) > 0
#           0                    si len(v) = 0

#sumar los elementos de v1 desde posicion 0 hasta el final -> sumaRecursiva2(v1, 0)
#sumar los elementos de v1 desde posicion 2 hasta el final -> sumaRecursiva2(v1, 2)
#.....
#sumar los elementos de v1 desde la ultima posicion hasta el final -> sumaRecursiva2(v1, len(v1))

def sumaRecursiva2(vector:np.array, posInicial:int=0)->int:
  sumaTotal = None
  if posInicial == len(vector)-1: #Si la posición inicial es el último elemento del vector:
    sumaTotal = vector[posInicial] #Sumo el último elemento a la suma total
  else:
    sumaTotal = vector[posInicial] + sumaRecursiva2(vector, posInicial+1) #Sino, sumo la posición en la que estoy e incremento la posición

  return sumaTotal

v1 = np.array([2,3,1,5,4])
print(sumaRecursiva2(v1))

15


In [ ]:
miVectorSolito[0]

45

In [ ]:
def sumaRecursiva(vectorAca:np.array)->int:
  sum = 0 #Inicializo la variable de salida como sum = 0
  if len(vectorAca) == 1: #Aca es la misma lógica de subvectores pero me detengo antes de quedarme sin elementos
    sum = sum + vectorAca[0]
  else:
    sum = vectorAca[0] + sumaRecursiva(vectorAca[1:])
    print(vectorAca[1:])
  return sum

vectorAca = [2,3,5,1,7,8,9]
#vectorAca[1:] -> [3,5,1,7,8,9]
#vectorAca[:1] -> [2]

### **Ejercicio 10**

Escribir una función que implemente de forma **recursiva** el algoritmo de **búsqueda binaria** sobre un vector.

https://es.khanacademy.org/computing/computer-science/algorithms/binary-search/a/binary-search

In [ ]:
#v tiene que estar ordenado
#busquedaBinaria(v,3) -> posicion del elemento 3 en v    si 3 esta en v
#                        None                            si 3 no esta en v
#v = [2,3,5,7,8,12,34,56]


  #busco posicion central
  #comparo datoBuscado con el elemento del vector en la posicion central
    # si el datoBuscado es igual -> lo encontre, es decir esta en la posicion central
    # si no es igual
      # si es menor -> busco el dato en la mitad inferior (0 - posicion central-1)
      # si es mayor -> busco el dato en la mitad superior (posicion central+1 - final)

def busquedaBinaria(vector:np.array, datoBuscado:int, posInicial:int, posFinal:int)->int:
  posDato = None #Inicio la variable posición de dato como nula
  centro = (posInicial+posFinal)//2 #Defino el centro como el indice central
  if posFinal < posInicial: #Si la posición final es mayor que la inicial:
    posDato = None #El resultado es nulo
  else: #Sino
    if vector[centro] == datoBuscado: #Si el valor central es el dato buscado:
      posDato = centro #La posición del dato es el valor central
    elif datoBuscado < vector[centro]: #Si el dato buscado es menor al dato central:
      posDato = busquedaBinaria(vector, datoBuscado, posInicial, centro-1) #Buscamos en el subvector izquierdo
    else: #Sino
      posDato = busquedaBinaria(vector, datoBuscado, centro+1, posFinal) #Buscamos en el subvector derecho
  return posDato #Devolvemos la posición del dato buscado

posInicial = 0
posFinal = 7
buscoAl = 37
miVector = np.array([3,7,12,15,24,37,42,54])

print(busquedaBinaria(miVector , buscoAl , posInicial , posFinal))

5


### **Ejercicio 11**

Escribir una función **recursiva** que retorna *True* si una cadena de caracteres es un palíndromo y *False* en caso contrario.

Nota: Palíndromo es la forma elegante de "capicua"

In [ ]:
#neuquen
# True             si   len(palabra) <= 1

['n','e','u','q','u','e','n']

def esPalindromo(palabra:np.array)->bool:
  salida = False #Inicializamos el valor como FALSO
  if len(palabra) < 2: #Si el tamaño de la palabra es 1:
    salida = True #Es palíndromo (por definción)
  else: #Sino
    salida = (palabra[0] == palabra[len(palabra)-1]) and esPalindromo(palabra[1:len(palabra)-1]) #Deben coincidir la primer letra y la última y además debe ser palíndromo la sub-palabra generada sin la primerletra y la última
    #            'n'            'n'                           esPalindromo('euque')
    #            'e'            'e'                           esPalindromo('uqu')
  return salida #Devuelvo la salida

p = np.array(['n','e','u','q','u','e','n'])
print(esPalindromo(p))

True


In [ ]:
def esPalindromo(unString:str)->bool:
  N = len(unString) #Asigno una variable con el tamanio de la palabra
  unString = unString.lower() #Convierto todas las letras a minúscula porque python distingue miúsculas de mayúsculas (opcional)
  if N < 2: #Si el tamanio es menor a 2:
    resultado = True #Es palíndromo por defincioón
  elif unString[0] == unString[-1]: #Si coinciden la primer letra y la última:
      resultado = esPalindromo(unString[1:N-1]) #Evalúo si el resto de la palabra es palíndromo
  else: #Sino
    resultado = False #No es palíndromo

  return resultado #Retorno el resultado booleano

print(esPalindromo("Neuquen"))
print(esPalindromo("AnitaLavaLaTina"))
print(esPalindromo("Alla"))
print(esPalindromo("Argentina"))

True
True
True
False


In [ ]:
len('AnitaLavaLaTina')

15

## **Matrices**

## **Declaracion de matrices**

In [ ]:
########### Bidimencionales ###########
print("########### Bidimencionales ###########")

matriz = np.zeros ((3,4), int) #filas y columnas

print("\nMatriz")
print(matriz)

########### Bidimencionales ###########

Matriz
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## **Acceso con indices / posiciones**

In [ ]:
########### Bidimencionales ###########
print("########### Bidimencionales ###########")

matriz[0][0] = 20
matriz[0][2] = 10
matriz[1][3] = 50

print("Matriz con modificaciones")
print(matriz)
print("Primer fila")
print(matriz[0])
print("Segunda fila")
print(matriz[1])
print("Elemento fila 1, columna 3")
print(matriz[1][3])
print("Columna 3")
print(matriz[:,3])

########### Bidimencionales ###########
Matriz con modificaciones
[[20  0 10  0]
 [ 0  0  0 50]
 [ 0  0  0  0]]
Primer fila
[20  0 10  0]
Segunda fila
[ 0  0  0 50]
Elemento fila 1, columna 3
50
Columna 3
[ 0 50  0]


## **Medicion de mediciones**

In [ ]:
print("Cantidad de filas")
print(len(matriz))

print("Cantidad de columnas")
print(len(matriz[0]))

print("Dimension de matriz")
print(matriz.shape)

(filas,columnas) = matriz.shape # en dos variables distintas
print(filas)
print(columnas)

Cantidad de filas
3
Cantidad de columnas
4
Dimension de matriz
(3, 4)
3
4


## **Recorridos de matrices**

In [ ]:
import numpy as np

matriz = np.array([[3,5,1],[2,8,14],[12,3,9],[23,4,0]]) # generamos matriz de 4 filas y 3 columnas

print(matriz)
print("\nRecorrido sobre elementos directamente (sentido directo)")
for fila in matriz: # en la primera iteracion entra a la primer fila
  for elemento in fila: # fila es un vector
    print(elemento)

print("\n", matriz)
print("Recorrido sobre elementos directamente (sentido inverso)")
for fila in reversed(matriz): # en la primera iteracion entra a la ultima fila
  for elemento in reversed(fila):
    print(elemento)

print("\n", matriz)
print("Recorrido usando indices / posiciones (sentido directo)")
for posicionFila in range(len(matriz)): #len de matriz es la cantidad de filas, y el  rango es 0,1,2 y 3
  for posicionColumna in range(len(matriz[posicionFila])): # para cada fila hacemos un rango por columnas, 0,1 y 2
    print("Posicion:", posicionFila,",", posicionColumna)
    print(matriz[posicionFila][posicionColumna])

print("\n", matriz)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicionFila in reversed(range(len(matriz))): #
  for posicionColumna in reversed(range(len(matriz[posicionFila]))):
    print("Posicion:", posicionFila,",", posicionColumna)
    print(matriz[posicionFila][posicionColumna])

### **Ejercicio 12**

Escribir una función que recibe las dimensiones y retorna una matriz rellena de la siguiente forma: En la posición ( n , m ) debe contener n + m.

Por ejemplo:

mat1 = rellenaMatriz(4,3)

=> mat1 =

| <!--   --> |Col 0|Col 1|Col 2|
|------------|:---:|:---:|:---:|
| **Fila 0** |  0  |  1  |  2  |
| **Fila 1** |  1  |  2  |  3  |
| **Fila 2** |  2  |  3  |  4  |
| **Fila 3** |  3  |  4  |  5  |

In [ ]:
def rellenaMatriz(nFilas:int, nCols:int)->np.array: #Definimos una función que toma un número de filas, un número de columnas y devuelve un array
  matrizSalida = np.zeros((nFilas,nCols), int) #Inicializo mi matriz como un arreglo de ceros (enteros) con los valores que le pasé por parámtero
  for nFila in range(nFilas): #Para cada número de fila en mi rango de número de filas:
    for nCol in range(nCols): #Para cada número de columna en mi rango de número de columnas:
      matrizSalida[nFila, nCol] = nFila+nCol #La matriz de salida en la ubicación "número de fila" "número de columna" será número de fila + número de columna
      # también podíamos hacer:
      # matrizSalida[nFila][nCol] = nFila+nCol
  return matrizSalida #Retornamos la matriz de salida

print(rellenaMatriz(4,3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


### **Ejercicio 13**

Escribir una función que recibe una matriz cuadrada (N x N) y calcula la suma de los elementos que están por encima de la diagonal principal (excluyendo la diagonal).

En el ejemplo de la imagen, la función deberia retornar: *b + c + f*

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-07-29-a-les-13.18.05-1.png)

In [ ]:
#nCol > nFila -> triangulo superior
#nCol == nFila -> diagonal pricipal
#nCol < nFila -> triangulo inferior

def suma_encima_diagonal(matriz): #Mi función toma como parámetro una matriz. Retorna un valor
  suma = 0 #Inicializo el valor de salida en cero
  nFilas, nCols = matriz.shape  #3,3 #es un PREREQUISITO que la matriz sea cuadrada, en este caso nFilas = nCols
  for posFila in range(nFilas): #0,1,2 #Para cada fila en el rango de filas
    for posCol in range(posFila+1, nCols): #range(2,3) -> 2 # Para cada columna en el rango de filas + 1 hasta nCols (es decir, no me interesan las columnas que sean menores que las filas)
      suma += matriz[posFila,posCol] #Sumo a mi valor de salida el valor alojado en esa posición
  return suma #Devolvemos el valor

def sumaTsuperior(matriz:np.array)->int:
  suma = 0
  nFilas, nCols = matriz.shape  #3,3
  for posFila in range(nFilas): #0,1,2
    for posCol in range(nCols): #0,1,2
      if posCol > posFila:
        suma += matriz[posFila,posCol]
  return suma

#Otra forma de verlo:

def sumaTriangularSuperior(matrizCuadrada:np.matrix)->int:
  N = len(matrizCuadrada) #Como la matriz es cuadrada es lo mismo pedir len o shape
  suma = 0 #Inicializo me falor de salida
  for fila in range(N-1): #Recorro todas las filas menos la última, porque es triangular superior.
    suma += matrizCuadrada[fila][fila + 1:].sum() # De cada fila, me quedo con los valores de la derecha del número de fila, es decir, con la triangular superior. Eso es un arreglo, del cual puedo sumar sus elementos.

  return suma #Devuelvo el valor de la suma

matriz = np.array([[1 , 2 , 3 , 4] , [4 , 5 , 6 , 7] , [7 , 8 , 9 , 10] , [11 , 12 , 13 , 14]])
print(matriz)
print(suma_encima_diagonal(matriz))
print(sumaTsuperior(matriz))
print(sumaTriangularSuperior(matriz))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]]
32
32
32


### **Ejercicio 14**

Escribir una función que retorna *True* si una matriz cuadrada es matriz diagonal y *False* en caso contrario.

Una matriz cuadrada diagonal es una matriz que tiene ceros en todos sus elementos, menos en la diagonal principal (No importan los elementos de la diagonal principal, pueden ser cero o no).

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es diagonal si:**

**M [ i , j ] == 0 para todo i != j**

Matriz diagonal de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  0  |  0  |  0  |  0  |
| **Fila 1** |  0  |  2  |  0  |  0  |
| **Fila 2** |  0  |  0  |  4  |  0  |
| **Fila 3** |  0  |  0  |  0  |  0  |

In [ ]:
def esDiagonal1(unaMatrizCuadrada:np.matrix)->bool:#Tomo una matriz cuadrada y devuelvo un valor booleano
  filas , columnas = unaMatrizCuadrada.shape #tomo la cantidad de filas y de columnas

  if filas != columnas: #Valido que la matriz sea cuadrada
    raise Exception('La matriz debe ser cuadrada!') #Lanzo una excepción en caso que no sea cuadrada

  N = filas #Podría ser columnas también, porque es cuadrada

  nElementos = N*(N-1) #La cantidad de elementos que me interesan validar son N al cuadrado (elementos totales del arreglo) menos los elementos de la diagonal, que son N, entonces: nElem = N**2-N = N*(N-1)
  elementosNulos = 0 #Inicializo un contador de elementos nulos. Espero al final de recorrer todo tener la misma cantidad de elemetnos nulos que elementos totales.

  for fila in range(N): #Para cada fila en el rango de filas
    for columna in range(N): #Para cada columna en el rango de columnas
      if fila == columna: #Si el número de fila es igual al número de columna
        pass #No me importa qué sucede
      elif fila != columna and unaMatrizCuadrada[fila][columna] == 0: #Si el número de fila es distinto al de la columna y ese elemento de matriz es nulo
        elementosNulos += 1 #Sumo uno a mis elementos nulos

  return elementosNulos == nElementos #Al final comparo si el número de elementos nulos es igual al número total de elementos fuera de la diagonal.

m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(esDiagonal1(m1))
print(m2)
print(esDiagonal1(m2))
print(m3)
print(esDiagonal1(m3))
print(m4)
print(esDiagonal1(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 0]
 [0 5 0]
 [7 0 9]]
False
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


In [ ]:
#Otra forma de verlo
def esDiagonal2(matrizCuadrada:np.array)->bool: #Defino mi función que tomará una matriz cuadrada y devolverá un booleano
  matrizD = True #Inicializo mi valor de salida en True
  nFilas, nCols = matrizCuadrada.shape #Me guardo las dimensiones de filas y columnas. COmo suponemos que la matriz es cuadrada tanto nFilas como nCols debe ser el mismo número
  nFila = 0 #Inicializo un contador
  while matrizD and nFila < nFilas-1: #Mientras matrizD sea True y nFila sea menor al número máximo de filas - 1:
    nCol = nFila+1 #El número de columna será el número de fila + 1. Con esto me aseguro de no pasar por la diagonal pues la fila será seimpre más grande que la columna por construcción
    while matrizD and nCol < nCols: #Mientras matrizD sea True y el número de columna sea menos al número máximo de columnas:
      if matrizCuadrada[nFila,nCol]!=0 or matrizCuadrada[nCol,nFila]!=0: #Si el elemento es distinto de cero tanto arriba como abajo de la diagonal (espejado)
        matrizD = False #Entonces la matriz no es diagonal
      nCol += 1 #Aumento el contador de columna
    nFila += 1 #Aumento el contador de fila
  return matrizD #Retorno el valor de verdad


m = np.array([[1,0,0,0],
              [0,1,0,0],
              [10,0,1,0],
              [0,0,0,1]])
esDiagonal2(m)
print(m1)
print(esDiagonal2(m1))
print(m2)
print(esDiagonal2(m2))
print(m3)
print(esDiagonal2(m3))
print(m4)
print(esDiagonal2(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 0]
 [0 5 0]
 [7 0 9]]
False
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


### **Ejercicio 15**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es simétrica y *False* en caso contrario.

Una matriz simétrica es como la de la imagen (no importan los elementos de la diagonal principal):

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-09-23-a-les-15.58.25.png)

Es decir:

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es simétrica si:**

**M [ i , j ] == M[ j, i ] para todo i != j**

Matriz simétrica de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  2  |  1  |  0  |  5  |
| **Fila 1** |  1  |  2  |  9  |  7  |
| **Fila 2** |  0  |  9  |  0  |  8  |
| **Fila 3** |  5  |  7  |  8  |  4  |

In [ ]:
def esSimetrica(unaMatrizCuadrada:np.matrix)->bool:
  filas , columnas = unaMatrizCuadrada.shape

  if filas != columnas:
    raise Exception('La matriz debe ser cuadrada!') #Lanzo una excepción si la matriz no es cuadrada

  N = filas #Podría ser columnas también
  nElementos = N*(N-1)/2 #Elementos en el triangulo superior o inferior. Se puede demostrar por inducción que N*(N-1) es siempre par
  elementosSimetricos = 0 #Inicializo el contador de elementos simétricos

  for fila in range(N): #Para cada fila en el rango de filas
    for columna in range(N): #Para cada columna en el rango de columnas
      if fila < columna and unaMatrizCuadrada[fila][columna] == unaMatrizCuadrada[columna][fila]: #Si el número de fila es menor que el número de columna (triangulo superior) y los elementos de matriz espejados son iguales:
        elementosSimetricos += 1 #Entonces sumo una unidad de elementos simétricos

  return elementosSimetricos == nElementos #Devuelvo si todos mis elementos son elementos simétricos


m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 7] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(esSimetrica(m1))
print(m2)
print(esSimetrica(m2))
print(m3)
print(esSimetrica(m3))
print(m4)
print(esSimetrica(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
False
[[1 0 0]
 [0 5 0]
 [0 0 9]]
True
[[1 0 7]
 [0 5 0]
 [7 0 9]]
True
[[0 0 0]
 [0 0 0]
 [0 0 0]]
True


In [ ]:
#Otra forma de verlo:
def esSimetrica(matriz:np.array)->bool: #Tomamos una matriz cuadrada y devolvemos un valor booleano
  matrizEsSimetrica = True #Inicializamos la variable de salida
  nFilas, nCols = matriz.shape #Guardamos las dimensiones
  for nFila in range(nFilas): #Para cada número de fila en el rango de filas
    for nCol in range(nCols): #Para cada número de columna en el rango de columnas
      if matriz[nFila,nCol] != matriz[nCol,nFila]: #Si los elementos de matriz espejados respecto de la diagonal no coinciden:
        matrizEsSimetrica = False #Entonces la matriz no es simétrica

  return matrizEsSimetrica #Devuelvo la conclusión

m=np.array([[2,1,0,5],
            [1,2,9,7],
            [0,9,0,8],
            [5,7,8,4]])
print(esSimetrica(m))

#m[1,2] = m[1][2]

True


### **Ejercicio 16**

Escribir una función **recursiva**, que calcule la suma de los elementos de la diagonal principal de una matriz.

Nota: La suma de los elementos de la diagonal principal de una matriz se llama "traza de la matriz".

Por ejemplo

Si mat1 =

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  2  |  1  |  0  |  5  |
| **Fila 1** |  1  |  2  |  9  |  7  |
| **Fila 2** |  0  |  9  |  0  |  8  |
| **Fila 3** |  5  |  7  |  8  |  4  |

=> **traza(mat1) = 2 + 2 + 0 + 4**

In [ ]:
def traza(unaMatriz:np.matrix)->int: #La traza es una función que recibe una matriz cuadrada y retorna un entero
  filas , columnas = unaMatriz.shape #Me guardo filas y columnas
  if filas != columnas: # Si la cantidad de filas es distinta a la cantidad de columnas:
    raise Exception('La matriz debe ser cuadrada!') #La matriz no es cuadrada!

  N = filas #Podría ser columnas también

  if N == 1: #Si la dimensión de la matriz es 1x1
    resultado = unaMatriz[0 , 0] #El resultado es trivial: la traza es el único elemento de la diagonal
  else: #Sino
    resultado = unaMatriz[N-1 , N-1] + traza(unaMatriz[:N-1 , :N-1]) #Tomo el último elemento de la matriz (que es el último de la diagonoal) y le sumo la traza de la sub-matriz resultante al eliminar la última fila y la última columna
    #resultado = unaMatriz[0 , 0] + traza(unaMatriz[1: , 1:]) #Es exactamente lo mismo
  return resultado #Devuelvo el resultado

m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 7] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(traza(m1))
print(m2)
print(traza(m2))
print(m3)
print(traza(m3))
print(m4)
print(traza(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
[[1 0 0]
 [0 5 0]
 [0 0 9]]
15
[[1 0 7]
 [0 5 0]
 [7 0 9]]
15
[[0 0 0]
 [0 0 0]
 [0 0 0]]
0


In [ ]:
def traza(matriz):
  suma = None
  if len(matriz) == 0:
    suma = 0
  else:
    suma = matriz[0, 0] + traza(matriz[1:, 1:])
  return suma

m1 = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
m2 = np.array([[1 , 0 , 0] , [0 , 5 , 0] , [0 , 0 , 9]])
m3 = np.array([[1 , 0 , 7] , [0 , 5 , 0] , [7 , 0 , 9]])
m4 = np.array([[0 , 0 , 0] , [0 , 0 , 0] , [0 , 0 , 0]])

print(m1)
print(traza(m1))
print(m2)
print(traza(m2))
print(m3)
print(traza(m3))
print(m4)
print(traza(m4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15
[[1 0 0]
 [0 5 0]
 [0 0 9]]
15
[[1 0 7]
 [0 5 0]
 [7 0 9]]
15
[[0 0 0]
 [0 0 0]
 [0 0 0]]
0


####**Ejercicio agregado**
Implementar una función recursiva para encontrar el máximo elemento de un arreglo

In [ ]:
#arreglo = [2,1,3,10,5,4,7]
#max(arreglo) = arreglo[0]                                si len(arreglo) = 1
#               maximo(arreglo[0] y max(arreglo[1:]))     si len(arreglo) > 1

#Suponemos que vector no esta vacio

def maximoEntre(unNumero , otroNumero):
  if unNumero > otroNumero:
    resultado = unNumero
  else:
    resultado = otroNumero
  return resultado

def maximoArreglo(vector:np.array)->int:
  maximo = None
  if len(vector) == 1:
    maximo = vector[0]
  else:
    maximoResto = maximoArreglo(vector[1:]) #maximoArreglo([1,3,10,5,4,7])...maximoArreglo([10,5,4,7])
    if vector[0] > maximoResto:
      maximo = vector[0]
    else:
      maximo = maximoResto
  return maximo

arreglo = [2,1,3,10,5,4,7]
print(maximoArreglo(arreglo))

10


####**Ejercicio agregado 2**
Implementar una función recursiva para encontrar la posicion del máximo elemento de un arreglo

In [ ]:
#arreglo = [2,1,3,10,5,4,7]
#posicionDelMaximo(array, posInicio) = posInicio       si posInicio = len(array)-1
#                                    = posicion del max(array[0], array[posicion maximo en el resto])

def posicionDelMaximo(vector:np.array, posInicio:int=0)->int:
  posMaximo = None
  if posInicio == len(vector)-1:
    posMaximo = posInicio
  else:
    posicionMaximoResto = posicionDelMaximo(vector, posInicio+1)
    if vector[posInicio] > vector[posicionMaximoResto]:
      posMaximo = posInicio
    else:
      posMaximo = posicionMaximoResto
  return posMaximo

arreglo = np.array([200,1,3,1000,5,400,70])
print(posicionDelMaximo(arreglo))


3
